name: Solstice Partners
favicon: null
layout_spectrum: 0.51137
typography_spectrum: 0.68417
title: 'Progressive Real Estate Development shop based in Baltimore, MD'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5e4d43'
    - '#8e961f'
    - '#877a71'
    - '#b0b563'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
