name: Solstice Partners
favicon: null
layout_spectrum: 0.4112625536508858
typography_spectrum: 0.10059169493615627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.12151187309063971
  lightness: 0.3023986420594156
  saturation: 0.48616530536673963
  rhythmicContrast: 0.6910719703882933
purpose: []
