name: Solstice Partners
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10059169493615627
title: 'Progressive Real Estate Development shop based in Baltimore, MD'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5e4d43'
    - '#8e961f'
    - '#877a71'
    - '#b0b563'
  brandStrength: 0.75
  lightness: 0.3023986420594156
  saturation: 0.48616530536673963
  rhythmicContrast: 0.6910719703882933
purpose: []
